config/routes.rb
Rails.application.routes.draw do
  root "projects#index"

  resources :posts, only: :index
  resources :projects, only: :index

  namespace "admin" do
    resources :projects, only: :index
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/audit_log.rb
class AuditLog < ApplicationRecord
  include Tenanted

  belongs_to :company
  belongs_to :user

  # TODO: polymorphic join to parent? useful if we are e.g. going to show history in UI
end

# == Schema Information
#
# Table name: audit_logs
#
#  id          :bigint           not null, primary key
#  action      :string
#  changelog   :string
#  model_class :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  company_id  :bigint           not null
#  model_id    :bigint
#  user_id     :bigint           not null
#
# Indexes
#
#  index_audit_logs_on_company_id  (company_id)
#  index_audit_logs_on_user_id     (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (company_id => companies.id)
#  fk_rails_...  (user_id => users.id)
#

app/models/company.rb
class Company < ApplicationRecord
  has_many :company_users, dependent: :destroy
  has_many :users, through: :company_users

  has_many :projects, dependent: :destroy # TODO: soft delete
  has_many :posts, through: :projects
end

# == Schema Information
#
# Table name: companies
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/company_user.rb
# TODO: could be tenanted, but probably no need...
class CompanyUser < ApplicationRecord
  belongs_to :company
  belongs_to :user

  has_many :posts # dependent: ? (soft delete)
end

# == Schema Information
#
# Table name: company_users
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  company_id :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_company_users_on_company_id  (company_id)
#  index_company_users_on_user_id     (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (company_id => companies.id)
#  fk_rails_...  (user_id => users.id)
#

app/models/concerns/audited.rb
# NOTE: I think audited is better than auditable as it always happens
module Audited
  extend ActiveSupport::Concern

  included do
    after_create :record_create
    after_update :record_update
    after_destroy :record_destroy
  end

  def record_create
    create("create")
  end

  def record_update
    create("update")
  end

  # TODO: soft delete...
  def record_destroy
    create("destroy")
  end

  private

  def create(action)
    AuditLog.create({
      user: Current.user,
      # TODO: confirm an untenanted model could be updated without Current.company
      company: Current&.company,
      action: action,
      model_class: self.class.name,
      model_id: id,
      changelog: changelog(action)
    })
  end

  # TODO: this could be cleverer - e.g. store before and after for strings
  def changelog(action)
    return nil unless action == "update"
    "Not recorded - implement custom changelog method in #{self.class.name}."
  end
end

app/models/concerns/tenanted.rb
module Tenanted
  extend ActiveSupport::Concern

  included do
    belongs_to :company, optional: true
    default_scope { where(company: Current.company_or_raise!) }
  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :company, :user

  class MissingCurrentCompany < StandardError; end

  def company_or_raise!
    msg = "You must set an company with Current.company="
    raise Current::MissingCurrentCompany, msg unless company

    company
  end

  # NOTE: intentionally blows up unless user is set first...
  def company=(company)
    raise unless user.company_users.map(&:company).include? company
    super
  end

  # TODO: bit weird? useful in tests...
  def company_user
    CompanyUser.find_sole_by(company: company, user: user)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  include Audited
  include Tenanted

  # TODO: not convinced this is better than :user
  belongs_to :company_user
  belongs_to :project
end

# == Schema Information
#
# Table name: posts
#
#  id              :bigint           not null, primary key
#  body            :string
#  title           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  company_id      :bigint           not null
#  company_user_id :bigint           not null
#  project_id      :bigint           not null
#
# Indexes
#
#  index_posts_on_company_id       (company_id)
#  index_posts_on_company_user_id  (company_user_id)
#  index_posts_on_project_id       (project_id)
#
# Foreign Keys
#
#  fk_rails_...  (company_id => companies.id)
#  fk_rails_...  (company_user_id => company_users.id)
#  fk_rails_...  (project_id => projects.id)
#

app/models/project.rb
class Project < ApplicationRecord
  include Tenanted

  belongs_to :company

  # NOTE: all company users are on all projects
  has_many :users, through: :company

  has_many :project_stakeholders, dependent: :destroy
  has_many :stakeholders, through: :project_stakeholders

  has_many :posts, dependent: :destroy # TODO: soft delete
end

# == Schema Information
#
# Table name: projects
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  company_id :bigint           not null
#
# Indexes
#
#  index_projects_on_company_id  (company_id)
#
# Foreign Keys
#
#  fk_rails_...  (company_id => companies.id)
#

app/models/project_stakeholder.rb
# TODO: should this be tenanted?
class ProjectStakeholder < ApplicationRecord
  belongs_to :project
  belongs_to :stakeholder
end

# == Schema Information
#
# Table name: project_stakeholders
#
#  id             :bigint           not null, primary key
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  project_id     :bigint           not null
#  stakeholder_id :bigint           not null
#
# Indexes
#
#  index_project_stakeholders_on_project_id      (project_id)
#  index_project_stakeholders_on_stakeholder_id  (stakeholder_id)
#
# Foreign Keys
#
#  fk_rails_...  (project_id => projects.id)
#  fk_rails_...  (stakeholder_id => stakeholders.id)
#

app/models/stakeholder.rb
class Stakeholder < ApplicationRecord
  has_many :project_stakeholders, dependent: :destroy
  has_many :projects, through: :project_stakeholders
end

# == Schema Information
#
# Table name: stakeholders
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/tenant.rb
# NOTE: equivalent to Apartment helper class
# TODO: should live somewhere else...
class Tenant
  def self.switch!(company, user)
    raise unless company && user
    Current.user = user
    Current.company = company
  end

  def self.switch_company!(company)
    raise unless company
    Current.company = company
  end

  # TODO: block versions?
end

app/models/user.rb
# cannot be tenanted - belongs to many companies...
class User < ApplicationRecord
  has_many :company_users, dependent: :destroy
  has_many :companies, through: :company_users
end

# == Schema Information
#
# Table name: users
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  before_action :stub_company

  def index
    @projects = Project.unscoped.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  # NOTE: this would happen as part of logging in / switching company
  # TODO: request based?
  def stub_company
    company_user = CompanyUser.unscoped.first
    Current.user = company_user.user
    Current.company = company_user.company
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :stub_company

  def index
    @posts = Post.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :stub_company

  def index
    @projects = Project.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/projects/index.html.erb
<div>
  <div class="mb-4 text-gray-400">
    Current user - <%= Current.user.name %> / <%= Current.company.name %>
  </div>
  <hr class="mb-4">

  <h1 class="font-bold text-4xl mb-4">
    All Projects
  </h1>

  <%= render collection: @projects, partial: "projects/project" %>
</div>

<div id="count">
  <%= pluralize @projects.count, "project" %> found
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plumbing</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <main class="container mx-auto mt-8 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_post.html.erb
<p class="mb-2">
  <%= post.title %> / <%= post.company.name %>

  <div class="text-gray-400 mb-2">
    Project - <%= post.project.name %>
  </div>

  <div class="text-gray-400 mb-4">
    User - <%= post.company_user.user.name %>
  </div>
</p>

app/views/posts/index.html.erb
<div>
  <div class="mb-4 flex justify-between">
    <div class="text-gray-400">
      Current user - <%= Current.user.name %> / <%= Current.company.name %>
    </div>
    <div>
      <%= link_to "Projects", projects_path %>
    </div>


  </div>
  <hr class="mb-4">

  <h1 class="font-bold text-4xl mb-4">
    Posts
  </h1>

  <%= render @posts %>
</div>

<div id="count">
  <%= pluralize @posts.count, "post" %> found
</div>

app/views/projects/_project.html.erb
<p class="mb-2">
  <%= project.name %> / <%= project.company.name %>

  <div class="text-gray-400 mb-2">
    Stakeholders - <%= project.stakeholders.map(&:name).join(", ") %>
  </div>

  <div class="text-gray-400 mb-2">
    Posts - <%= project.posts.map(&:title).join(", ") %>
  </div>

  <div class="text-gray-400 mb-4">
    Users - <%= project.users.map(&:name).join(", ") %>
  </div>
</p>

app/views/projects/index.html.erb
<div>
  <div class="mb-4 text-gray-400">
    Current user - <%= Current.user.name %> / <%= Current.company.name %>
  </div>
  <hr class="mb-4">

  <h1 class="font-bold text-4xl mb-4">
    Projects
  </h1>

  <%= render @projects %>
</div>

<div id="count">
  <%= pluralize @projects.count, "project" %> found
</div>